### ISSUE TITLE
[Question] Skip Alignment? 

### ISSUE THREAD

**Issue by cloudlakecho** [zhouyuchong/face-recognition-deepstream#22]
Hello;

I try to run "test/face_test_demo.py" without [Alignment](https://github.com/zhouyuchong/face-recognition-deepstream#alignment) step. I followed all steps in [Usage](https://github.com/zhouyuchong/face-recognition-deepstream#usage) and able to execute the code. 

Unfortunately, the output included errors of "failed to build network since there is no model file matched." :
```
isi@D-003:~/project/face-recognition-deepstream/test$ python3 face_test_demo.py 
--------- start app
Unknown or legacy key specified 'alignment' for group [property]
Unknown or legacy key specified 'user-meta' for group [property]
localhost;9092;deepstream
(True, 'success, state <enum GST_STATE_CHANGE_SUCCESS of type Gst.StateChangeReturn>')
-----------------------------------------------------------------------------
set index of src task-0 to 0
add set return : <enum GST_STATE_CHANGE_NO_PREROLL of type Gst.StateChangeReturn>
Starting pipeline 


**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

0:00:13.096044384  7044 0xfffecc008c60 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<secondary-nvinference-engine> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 2]: deserialized trt engine from :/home/isi/pre_trained/arm/arcface-r100.engine
INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x112x112       
1   OUTPUT kFLOAT prob            512x1x1         

0:00:13.263057216  7044 0xfffecc008c60 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<secondary-nvinference-engine> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 2]: Use deserialized engine model: /home/isi/pre_trained/arm/arcface-r100.engine
0:00:13.283955808  7044 0xfffecc008c60 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<secondary-nvinference-engine> [UID 2]: Load new model:/home/isi/project/face-recognition-deepstream/src/kbds/configs/face/config_arcface.txt sucessfully
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
~~ CLOG[/dvs/git/dirty/git-master_linux/deepstream/sdk/src/utils/nvmultiobjecttracker/include/modules/NvMultiObjectTracker/NvTrackerParams.hpp, getConfigRoot() @line 52]: [NvTrackerParams::getConfigRoot()] !!![WARNING] Invalid low-level config file caused an exception, but will go ahead with the default config values
gstnvtracker: Batch processing is ON
gstnvtracker: Past frame output is OFF
~~ CLOG[/dvs/git/dirty/git-master_linux/deepstream/sdk/src/utils/nvmultiobjecttracker/include/modules/NvMultiObjectTracker/NvTrackerParams.hpp, getConfigRoot() @line 52]: [NvTrackerParams::getConfigRoot()] !!![WARNING] Invalid low-level config file caused an exception, but will go ahead with the default config values
[NvMultiObjectTracker] Initialized
0:00:13.495362912  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1170> [UID = 1]: Warning, OpenCV has been deprecated. Using NMS for clustering instead of cv::groupRectangles with topK = 20 and NMS Threshold = 0.5
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

0:00:16.779126688  7044 0xfffecc008c60 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 1]: deserialized trt engine from :/home/isi/pre_trained/arm/retina_r50.engine
INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x480x640       
1   OUTPUT kFLOAT prob            189001x1x1      

0:00:16.958094368  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::checkBackendParams() <nvdsinfer_context_impl.cpp:1841> [UID = 1]: Backend has maxBatchSize 1 whereas 16 has been requested
0:00:16.958145376  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2018> [UID = 1]: deserialized backend context :/home/isi/pre_trained/arm/retina_r50.engine failed to match config params, trying rebuild
0:00:16.964277568  7044 0xfffecc008c60 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1923> [UID = 1]: Trying to create engine from model files
ERROR: failed to build network since there is no model file matched.
ERROR: failed to build network.
0:00:18.778852512  7044 0xfffecc008c60 ERROR                nvinfer gstnvinfer.cpp:640:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1943> [UID = 1]: build engine file failed
0:00:18.940563936  7044 0xfffecc008c60 ERROR                nvinfer gstnvinfer.cpp:640:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2029> [UID = 1]: build backend context failed
0:00:18.941227200  7044 0xfffecc008c60 ERROR                nvinfer gstnvinfer.cpp:640:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1266> [UID = 1]: generate backend failed, check config file settings
0:00:18.942414528  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:846:gst_nvinfer_start:<primary-inference> error: Failed to create NvDsInferContext instance
0:00:18.942426016  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:846:gst_nvinfer_start:<primary-inference> error: Config file path: /home/isi/project/face-recognition-deepstream/src/kbds/configs/face/config_retinaface.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
Traceback (most recent call last):
  File "/home/isi/project/face-recognition-deepstream/test/../src/kbds/core/pipeline.py", line 122, in bus_call_abs
    search_index = search_index[0].split('-')[2][:-1]
TypeError: 'NoneType' object is not subscriptable
[NvMultiObjectTracker] De-initialized
(True, 'success')
src: <Stream task-0 task-0-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0xffff3dc4b840 (GstURIDecodeBin at 0x2000780)>
<enum GST_STATE_CHANGE_NO_PREROLL of type Gst.StateChangeReturn>

**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

set index of src task-5 to 1
add set return : <enum GST_STATE_CHANGE_NO_PREROLL of type Gst.StateChangeReturn>
(True, 'success')
src: <Stream task-5 task-5-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0xfffeed98bdc0 (GstURIDecodeBin at 0x2001ce0)>
<enum GST_STATE_CHANGE_SUCCESS of type Gst.StateChangeReturn>
Traceback (most recent call last):
  File "/home/isi/project/face-recognition-deepstream/test/../src/kbds/core/pipeline.py", line 498, in cb_decodebin_child_added
    obj.set_property("gpu_id", self.gpu_id)
TypeError: object of type `nvv4l2decoder' does not have property `gpu_id'
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
gstname= video/x-raw
pad name:  sink_1
Decodebin linked to pipeline

**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

^CTraceback (most recent call last):
  File "face_test_demo.py", line 84, in <module>
    time.sleep(1)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

It looks like code couldn't read ENGINE file (pre trained neural network weight) for the first neural network. The first neural network the RetinaFace and the same weight is actually work at [similar code of the programmer of this repository](https://github.com/zhouyuchong/retinaface-deepstream-python). 

I built the weight followed [the suggestion](https://github.com/zhouyuchong/face-recognition-deepstream/issues/21#issuecomment-1439383472) in my hardware.

This is my configuration file for RetinaFace, "config_retinaface.txt":
```
[property]

gpu-id=0
#0=RGB, 1=BGR
model-color-format=1
model-engine-file=/home/isi/pre_trained/arm/retina_r50.engine
labelfile-path=/home/isi/project/face-recognition-deepstream/models/retinaface/labels.txt

process-mode=1
## 0=FP32, 1=INT8, 2=FP16 mode
network-mode=2
gie-unique-id=1
network-type=0
output-blob-names=prob
## 0=Group Rectangles, 1=DBSCAN, 2=NMS, 3= DBSCAN+NMS Hybrid, 4 = None(No clustering)
#cluster-mode=2
maintain-aspect-ratio=1
batch-size=32
num-detected-classes=1
output-tensor-meta=1

# custom detection parser
parse-bbox-func-name=NvDsInferParseCustomRetinaface
custom-lib-path=/home/isi/project/face-recognition-deepstream/models/retinaface/nvdsinfer_customparser/libnvdsinfer_custom_impl_retinaface.so
net-scale-factor=1.0
offsets=104.0;117.0;123.0
force-implicit-batch-dim=0
# number of consecutive batches to skip for inference
interval=0


[class-attrs-all]
# bbox threshold
pre-cluster-threshold=0.6
# nms threshold
# post-cluster-threshold=0.4
nms-iou-threshold=0.5
```
Do I miss any step? 

Any suggestion will be appreciated. 

Thank you.

Runtime environment:
&nbsp;&nbsp; OS: Ubuntu 20.04 in AArch 64 (Arm)
&nbsp;&nbsp; DeepStream: 6.1
&nbsp;&nbsp; Python: 3.8

**Comment by cloudlakecho** [comment]
As reference, this is runtime output of [the retinaface-deepstream-python](https://github.com/zhouyuchong/retinaface-deepstream-python}, which called only RetinaFace:

```
(.venv_3_8) isi@D-003:~/project/retinaface-deepstream-python$ python main.py rtsp://isi:1Password1@192.168.3.25:554/stream2
main.py:270: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Creating Pipeline 
 
Creating streamux 
 
Creating source_bin  0  
 
Creating source bin
source-bin-00
Creating Pgie 
 
Creating tiler 
 
Creating nvvidconv 
 
Creating nvosd 
 
Creating transform 
 
Creating EGLSink 

Atleast one of the sources is live
WARNING: Overriding infer-config batch-size 32  with number of sources  1  

Adding elements to Pipeline 

Linking elements in the Pipeline 

main.py:400: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  loop = GObject.MainLoop()
Now playing...
1 :  rtsp://isi:1Password1@192.168.3.25:554/stream2
Starting pipeline 


Using winsys: x11 
0:00:00.218154016  8964      0x41eaa00 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1170> [UID = 1]: Warning, OpenCV has been deprecated. Using NMS for clustering instead of cv::groupRectangles with topK = 20 and NMS Threshold = 0.5
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
0:00:03.694811520  8964      0x41eaa00 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 1]: deserialized trt engine from :/home/isi/pre_trained/arm/retina_r50.engine
INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x480x640       
1   OUTPUT kFLOAT prob            189001x1x1      

0:00:03.860644064  8964      0x41eaa00 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 1]: Use deserialized engine model: /home/isi/pre_trained/arm/retina_r50.engine
0:00:03.892832576  8964      0x41eaa00 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<primary-inference> [UID 1]: Load new model:retinaface_config.txt sucessfully
Decodebin child added: source 

Decodebin child added: decodebin0 

Decodebin child added: rtph264depay0 

Decodebin child added: h264parse0 

Decodebin child added: capsfilter0 

Decodebin child added: nvv4l2decoder0 

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
In cb_newpad

gstname= video/x-raw
features= <Gst.CapsFeatures object at 0xfffed30e2280 (GstCapsFeatures at 0xfffe200c84a0)>
```

**Comment by zhouyuchong** [comment]
@cloudlakecho Hi, the output log showed the reason
```
0:00:16.958094368  7044 0xfffecc008c60 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::checkBackendParams() <nvdsinfer_context_impl.cpp:1841> [UID = 1]: Backend has maxBatchSize 1 whereas 16 has been requested

```
seems your engine file was generated with batchsize=1, however, the config file requires a pretrained model with batchsize=16.

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks! That is a great catch. 

I will review all parameters including the batch size and try again. 

By the way, is possible to skip [Alignment step](https://github.com/zhouyuchong/face-recognition-deepstream#alignment)?
&nbsp;&nbsp;  I am not considering recognition performance at this moment.

**Comment by zhouyuchong** [comment]
> @zhouyuchong Thanks! That is a great catch.
> 
> I will review all parameters including the batch size and try again.
> 
> By the way, is possible to skip [Alignment step](https://github.com/zhouyuchong/face-recognition-deepstream#alignment)?    I am not considering recognition performance at this moment.

Of cource you can skip alignment step. just use default **gst-nvinfer** will be ok.
